apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container     #Name of container not matter
        image: solankv1/python-app:v2
        ports:
        - containerPort: 8000

